version: '3.8'

services:
  # Frontend web application - using live GCP API
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: igdb-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://igdb-recommendation-api-dev-5wxthq523q-ew.a.run.app

  # Cloud SQL Proxy for connecting to GCP development database
  # Uncomment when needed for GCP integration
  # cloudsql-proxy:
  #   image: gcr.io/cloudsql-docker/gce-proxy:latest
  #   container_name: igdb-cloudsql-proxy
  #   command:
  #     - "/cloud_sql_proxy"
  #     - "-instances=${GCP_PROJECT_ID}:${GCP_REGION}:${DB_INSTANCE_NAME}=tcp:0.0.0.0:5433"
  #     - "-credential_file=/secrets/cloudsql/credentials.json"
  #   volumes:
  #     - ./secrets/cloudsql:/secrets/cloudsql
  #   ports:
  #     - "5433:5433"
